enum class Pokemon_Types
{
    Normal_Type,
    Fire_Type,
    Water_Type,
    Electric_Type,
    Grass_Type,
    Ice_Type,
    Fighting_Type,
    Poison_Type,
    Ground_Type,
    Flying_Type,
    Psychic_Type,
    Bug_Type,
    Rock_Type,
    Ghost_Type,
    Dragon_Type,
    Dark_Type,
    Steel_Type,
    Fairy_Type
};